quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=sifra
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/helpdesk_db

quarkus.http.port=8082

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8081/realms/help-desk-system
quarkus.oidc.client-id=help-desk-system
quarkus.oidc.credentials.secret=RmYjHhWf39LVHydR5FjgGvhHB8B2oV4r
quarkus.oidc.application-type=service

quarkus.rest-client.ip-api.url=https://api.ipify.org
quarkus.rest-client.ip-api.scope=jakarta.inject.Singleton

quarkus.rest-client.timezone-api.url=https://timeapi.io
quarkus.rest-client.timezone-api.scope=jakarta.inject.Singleton